RichwoodNew/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Include_in_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Forecast</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Account_Yearly_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Yearly Forecasts</relationshipLabel>
        <relationshipName>Account_Yearly_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecast_Period_Start__c</fullName>
        <label>Forecast Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Forecast_Status__c</fullName>
        <label>Forecast Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Adjustment Requested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Budgeted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <summarizedField>Forecast_Product_Category__c.Projected_Amount__c</summarizedField>
        <summaryForeignKey>Forecast_Product_Category__c.Account_Yearly_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Account Yearly Forecast</label>
    <nameField>
        <label>Account Yearly Forecast</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Yearly Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Forecast_Product_Category__c.object
<CustomObject>
    <fields>
        <fullName>Account_Yearly_Forecast__c</fullName>
        <label>Account Yearly Forecast</label>
        <referenceTo>Account_Yearly_Forecast__c</referenceTo>
        <relationshipLabel>Product Categories in this Forecast</relationshipLabel>
        <relationshipName>Forecast_Product_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <referenceTo>Product_Category__c</referenceTo>
        <relationshipLabel>Forecasts Against this Product Category</relationshipLabel>
        <relationshipName>Forecast_Product_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Projected Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Forecast Product Category</label>
    <nameField>
        <displayFormat>FPC{00000}</displayFormat>
        <label>Forecast Product Category</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <label>Quote Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Replacement Parts</fullName>
                </value>
                <value>
                    <fullName>New Equipment</fullName>
                </value>
                <value>
                    <fullName>Engineering Review</fullName>
                </value>
                <value>
                    <fullName>Labor Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Product_Category__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-Belt Cleaners</fullName>
                </value>
                <value>
                    <fullName>2-Replacement Blades</fullName>
                </value>
                <value>
                    <fullName>3-Plows</fullName>
                </value>
                <value>
                    <fullName>4-Parts</fullName>
                </value>
                <value>
                    <fullName>5-Impact Bed Components</fullName>
                </value>
                <value>
                    <fullName>6-Material Containment</fullName>
                </value>
                <value>
                    <fullName>7-Wear Liners</fullName>
                </value>
                <value>
                    <fullName>8-Other</fullName>
                </value>
                <value>
                    <fullName>1-Belt Cleaners_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>2-Replacement Blades_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>3-Plows_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>4-Parts_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>5-Impact Bed Components_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>6-Material Containment_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>7-Wear Liners_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>8-Other_</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RichwoodNew/src/classes/Test_SalesForecasts_ctrl.cls
@isTest
public class Test_SalesForecasts_ctrl{
    static testMethod void test() {
        User u1 = [SELECT Id FROM User WHERE name='Judd Roseberry'];
        Account a = new Account();
        a.name = 'test';
        a.ownerId = u1.Id;
        a.Include_in_Forecast__c = true;
        insert a;
        
        Account_Yearly_Forecast__c ayfc = new  Account_Yearly_Forecast__c();
        ayfc.Account__c = a.Id;
        ayfc.Forecast_Period_Start__c = system.today().addYears(1);
        ayfc.Forecast_Status__c = 'Submitted';
        ayfc.name = 'test';
        insert  ayfc;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = a.Id;
        opp.Amount = 3000;
        opp.Name = 'testopp1';
        opp.CloseDate  = system.today().addYears(1);
        opp.StageName = 'Qualification';
        opp.Quote_Type__c='Labor Only';
        insert opp;
        
        Opportunity oppclose = new Opportunity();
        oppclose.AccountId = a.Id;
        oppclose.Amount = 4000;
        oppclose.Name = 'testopp1';
        oppclose.CloseDate  = system.today();
        oppclose.StageName = 'Closed Lost';
        oppclose.Quote_Type__c='Labor Only';
        insert oppclose;
        
         Product_Category__c pcc = new Product_Category__c();
         pcc.Description__c = 'Uploaded';
         pcc.Type__c = '4-Parts';
         insert pcc;
        
        Forecast_Product_Category__c fpc = new Forecast_Product_Category__c();
        fpc.Units__c = 1234;
        fpc.Projected_Amount__c = 226;
        fpc.Account_Yearly_Forecast__c = ayfc.Id ;
        fpc.Product_Category__c = pcc.Id ;
        insert fpc;
        
        SalesForecasts_ctrl cntrl = new SalesForecasts_ctrl();
        //cntrl.getGetOption();
        cntrl.setFilter();
        cntrl.defaultDateTest='01/01/2017';
        cntrl.dateChange();
        cntrl.customDateChange();
        cntrl.updateSortDirection();
        cntrl.sortDirection='asc';
        cntrl.currentField='accName';
        cntrl.updateSortDirection();
        cntrl.currentField='Forecast_Status';
        cntrl.updateSortDirection();
        cntrl.currentField='cwSum_2year';
        cntrl.updateSortDirection();
        cntrl.currentField='cwSum_1year';
        cntrl.updateSortDirection();
        cntrl.currentField='pAmountSum';
        cntrl.updateSortDirection();
        cntrl.currentField='cwSum';
        cntrl.updateSortDirection();
        cntrl.currentField='openSum';
        cntrl.updateSortDirection();
        
        
       
}
        
}