RichwoodNew/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Include_in_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Forecast</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Product_Category__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-Belt Cleaners</fullName>
                </value>
                <value>
                    <fullName>2-Replacement Blades</fullName>
                </value>
                <value>
                    <fullName>3-Plows</fullName>
                </value>
                <value>
                    <fullName>4-Parts</fullName>
                </value>
                <value>
                    <fullName>5-Impact Bed Components</fullName>
                </value>
                <value>
                    <fullName>6-Material Containment</fullName>
                </value>
                <value>
                    <fullName>7-Wear Liners</fullName>
                </value>
                <value>
                    <fullName>8-Other</fullName>
                </value>
                <value>
                    <fullName>1-Belt Cleaners_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>2-Replacement Blades_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>3-Plows_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>4-Parts_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>5-Impact Bed Components_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>6-Material Containment_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>7-Wear Liners_</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>8-Other_</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RichwoodNew/src/classes/Test_AccountForecastbyCustomerController.cls
@isTest
public class Test_AccountForecastbyCustomerController {
    static testMethod void test() {
         User u1 = [SELECT Id FROM User WHERE name='Judd Roseberry'];
            
         Account a = new Account(name = 'test',ownerId = u1.Id,Include_in_Forecast__c = true);
         insert a;
        
        insert new Product_Category__c(Description__c = 'Uploaded',Type__c = '4-Parts');
        insert new Product_Category__c(Description__c = 'Uploaded');
        
        ApexPages.CurrentPage().getParameters().put('Id',a.id);
        ApexPages.CurrentPage().getParameters().put('year','2017');
        AccountForecastbyCustomerController obj = new AccountForecastbyCustomerController();
        Obj.InitializingData();
        
        Obj.projectType='None';
        Obj.projectIdx=0;
        Obj.updateForecast();
        
        Obj.previous();
        Obj.next();
        Obj.SubmitForecast();
        
        //Creating Capital Project
        Obj.createNewCapitalProject();
        Obj.capitalprojectidx=0;
        Obj.capitalProject_List[0].capitalProject.Name='Test';
        Obj.updateCapitalProject();
        
        // Creating Capital Project Forecast Object
        Obj.createNewCapitalForecast();
        
        // Updating Capital Project        
        Obj.capitalProject_List[0].capitalProject.Status__c='Complete';
        Obj.updateCapitalProject();
        
        Obj.save();
    }
}