RichwoodNew/src/objects/Account_Yearly_Forecast__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Yearly Forecasts</relationshipLabel>
        <relationshipName>Account_Yearly_Forecasts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Budgeted_Sales__c</fullName>
        <label>Budgeted Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Forecast_Period_Start__c</fullName>
        <label>Forecast Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Projected_Amount__c</fullName>
        <label>Projected Amount</label>
        <summarizedField>Forecast_Product_Category__c.Projected_Amount__c</summarizedField>
        <summaryForeignKey>Forecast_Product_Category__c.Account_Yearly_Forecast__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Account Yearly Forecast</label>
    <nameField>
        <label>Account Yearly Forecast</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Yearly Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RichwoodNew/src/classes/SalesForecastCSVExport_ctrl.cls
public class SalesForecastCSVExport_ctrl {
	public List<AggregateResult> AggregateResult_list {get;set;}
    public integer year{get;set;}
    public SalesForecastCSVExport_ctrl(){
        AggregateResult_list = new list<AggregateResult>();
        try{
        	Year = Integer.valueOf(apexpages.currentpage().getparameters().get('year'));
        	AggregateResult_list.addall([ select Account__r.owner.id, Account__r.owner.name ownername, Account__r.owner.SalesRepId1__c repid, sum(Budgeted_Sales__c)Budgeted_Sales , sum(Projected_Amount__c)Projected_Amount from Account_Yearly_Forecast__c WHERE CALENDAR_YEAR(Forecast_Period_Start__c) =:year group by Account__r.owner.id, Account__r.owner.name, Account__r.owner.SalesRepId1__c ]);            
        }catch(exception e){
            system.debug(e);
        }            
    }
}