RichwoodNew/src/objects/Division__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Divisions</relationshipLabel>
        <relationshipName>Divisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Division</label>
    <nameField>
        <label>Division</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RichwoodNew/src/classes/QuickServiceRequest_Ctrl_Test.cls
@isTest
public class QuickServiceRequest_Ctrl_Test {
    public static testmethod void caseOne(){
        QuickServiceRequest_Ctrl Obj=new QuickServiceRequest_Ctrl();
        Obj.newAccount();
        Obj.cancelAccount();
        Obj.newAccount();
        Obj.account_Obj.Name='Test';
        Obj.saveAccount();
        
        Obj.editAccount();
        Obj.account_Obj.Name='Test';
        Obj.cancelAccount();
        
        Obj.newContact();
        Obj.contact_Obj.lastName='Test';
        Obj.saveContact();
        Obj.editContact();
        Obj.cancelContact();
        
        Obj.newQRSBttn();
        Obj.Property_Location();
        Obj.saveQRS();
        Obj.cancelQRS();
        
        Obj.newQRSBttn();
        Obj.newProperty();
        Obj.cancelProperty();
        Obj.newProperty();
        Obj.saveProperty();
        
        Obj.newDivision();
        Obj.Property_Location=[select id from Location__c limit 1].id;
        Obj.saveDivision();
        Obj.cancelDivision();
        
		Obj.Division_so();        
       
        Obj.newConveyor();
        Obj.cancelConveyor();
        Obj.newConveyor();
		Obj.division=[select id from Division__c limit 1].id;
        Obj.saveConveyor();
        
        Obj.newQRSContact();
        Obj.QRScontact_Obj.lastName='Test';
        Obj.cancelQRSContact();
        
        
        
        Obj.newQRSContact();
        Obj.QRScontact_Obj.lastName='Test';
        Obj.saveQRSContact();
        Obj.saveQRS();
        
        
    }
}