RichwoodNew/src/objects/Saddle__c.object
<CustomObject>
    <fields>
        <fullName>Belt_Speed__c</fullName>
        <label>Belt Speed</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Belt_Width__c</fullName>
        <label>Belt Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bolt_Centers__c</fullName>
        <label>Bolt Centers</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Center_Height__c</fullName>
        <label>Center Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chord_Length__c</fullName>
        <label>Chord Length</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drop_Height__c</fullName>
        <label>Drop Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Idler_in_Load_Zone__c</fullName>
        <label>Idler in Load Zone?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAX_Lump_Size__c</fullName>
        <label>MAX Lump Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Material_Density__c</fullName>
        <label>Material Density</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saddle__c</fullName>
        <label>Saddle</label>
        <length>220</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tons_per_Hour__c</fullName>
        <label>Tons per Hour</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trough_Angle__c</fullName>
        <label>Trough Angle</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wing_Height__c</fullName>
        <label>Wing Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Saddle</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Saddle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saddles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RichwoodNew/src/objects/Specifications_Data_Base__c.object
<CustomObject>
    <label>Specifications Data Base</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Specifications Data Base</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Specifications Data Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RichwoodNew/src/classes/TestSaddleandIdlerLookup_ctrl.cls
@isTest
public class TestSaddleandIdlerLookup_ctrl {
    public static testmethod void CaseOne(){
        List<sObject> ls = Test.loadData(Specifications_Data_Base__c.sObjectType, 'Specifications_Data_Base');
        //system.debug(ls);
        //insert ls;
        System.debug(ls.size());
        Saddle__c s = new Saddle__c();
        insert s;
        SaddleandIdlerLookup_ctrl sl= new SaddleandIdlerLookup_ctrl(new ApexPages.StandardController(s));
        PageReference pageRef = Page.SaddleandIdlerLookup;
        Test.setCurrentPage(pageRef);
        sl.unload();
        sl.saddle.Belt_Width__c=24;
        sl.initialize();
        sl.saddle.Belt_Speed__c=30;
        sl.initialize();
        sl.saddle.Tons_per_Hour__c=20;
        sl.initialize();
        sl.saddle.Material_Density__c='Copper';
        sl.unload();
        sl.saddle.MAX_Lump_Size__c=20;
        sl.unload();
        sl.saddle.Drop_Height__c=20;
        sl.unload();
        sl.saddle.Trough_Angle__c=25;
        sl.unload();
        sl.saddle.Bolt_Centers__c=20;
        sl.unload();
        sl.saddle.Center_Height__c=20;
        sl.unload();
        sl.saddle.Wing_Height__c=20;
        sl.unload();
        sl.saddle.Chord_Length__c=20;
        sl.unload();
        sl.saddle.Idler_in_Load_Zone__c='yes';
        sl.unload();
    }
}